language: node_js
node_js:
  - "4.4.3"
before_install:
  - cd frontend
before_script:
  - npm install -g gulp
script:
  - npm run testbuild
  - gulp release-package
after_success:
  - codeclimate-test-reporter < ./frontend/coverage/lcov-frontend-remapped.info
  - 'cat ./frontend/coverage/lcov-frontend-remapped.info | ./frontend/node_modules/.bin/coveralls'