language: node_js
node_js:
  - "4.4.3"
before_install:
  - cd frontend
before_script:
  - npm install -g gulp
script: 
  - gulp release-package
after_success:
  - 'cat ./coverage/lcov-frontend-backend-remapped.info | ./node_modules/.bin/coveralls'