language: node_js
node_js:
  - "6"
before_install:
  - cd frontend
before_script:
  - npm install -g gulp
script:
  - gulp release-package
notifications:
  slack: coditproducts:j1aqpLDXRWKFO7x07wkMWIrx